### PR TITLE
fix opengl and add developer name

### PR DESCRIPTION
**Pull request by Lonsfor**
turn off `gllog` so that  opengl works (#2) and add developer name to the metadata

### CODE REVIEW

**Comment by cbm755** [comment]
LGTM, I'll test later and then merge

**Comment by cbm755** [comment]
Actually I'm not completely sure how to test this.  On my local machine last time I tried `-opengl` but the game still had sprites---shouldn't it have 3d models?

**Comment by Lonsfor** [comment]
you need to turn on 3d models on the opengl menu
kart0000
here is a gif example of it turned on with a custom racer
kart0004

**Comment by ghisvail** [comment]
@cbm755 Indeed, you have to turn them on manually from the video options. Looks good to me too.

**Comment by ghisvail** [comment]
Another option could have been to just run a `sed` command to perform the substitution instead of a patch.

**Pull request merged**
