### PR TITLE
update to 1.3

### PR DESCRIPTION
**Pull request by Lonsfor**
was able to launch in opengl play time attack, view the replay and join an online game.

only issue is that there was a change in the master server so you might need to change it manually with `masterserver "https://ms.kartkrew.org/ms/api"` in game console.

### CODE REVIEW

**Comment by Lonsfor** [comment]
also the change log said something about Discord Rich Presence? should the package have it or not?

currently it seems to not be the build

**Comment by cbm755** [comment]
Re: Discord thing: I saw that too but upstream says "not support on Linux" so I ignored it.

We should make an effort to push the .metainfo.xml file upstream: I don't think this flatpak repo should be maintaining such an extensive changelog.  (Just a general comment, no need to change your PR).

I also tested opengl time attack and joined a server.  LGTM!   So +1 to merge, will do so in 24 hours or @ghisvail you can merge it faster if you want to.

**Comment by Lonsfor** [comment]
> but upstream says "not support on Linux"

maybe by that they meant not enabled bu default. because i got a local non-flatpack build of it working.

**Comment by ghisvail** [comment]
> We should make an effort to push the .metainfo.xml file upstream: I don't think this flatpak repo should be maintaining such an extensive changelog. (Just a general comment, no need to change your PR).

I agree. Change logs should better be written upstream where the info is.

**Comment by ghisvail** [comment]
Thanks!

**Comment by Lonsfor** [comment]
i dont think upstream would care to maintain the metainfo.xml considering the state the ppa is in

**Comment by cbm755** [comment]
Maybe we can have each metainfo.xml release description point to their gitlab releases...  I might do MR for this if I get a chance.

**Comment by ghisvail** [comment]
Sorry, I am late to the party.

> i dont think upstream would care to maintain the metainfo.xml considering the state the ppa is in

Indeed, Linux is not exactly their target priority.

> Maybe we can have each metainfo.xml release description point to their gitlab releases... I might do MR for this if I get a chance.

That's a great idea.

**Pull request merged**
