### PR TITLE
Update to latest commit on master

### LINKED ISSUE #7: Cannot connect to the Master Server
server browser doesnt work in current release, there is a fix but it is in master. also there is a fix for opengl so the patch could also be removed.

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #7

### CODE REVIEW

**Comment by ghisvail** [comment]
@Lonsfor could you try this build and report whether #7 is fixed for you please? Cheers.

**Comment by Lonsfor** [comment]
was able to launch in opengl, open the server browser and join a game. seems good :+1:

**Comment by cbm755** [comment]
I also tested with `-opengl`, server browser works too.  +1 to merge.

**Comment by ghisvail** [comment]
Thanks folks for checking it out.

**Pull request merged**
