### PR TITLE
Fixed 'Wrong size for extra data' error

### PR DESCRIPTION
**Pull request by anthonyajumelles**

### CODE REVIEW

**Comment by cbm755** [comment]
Thanks!  Did the sha change to or did we just get the file size wrong?

**Comment by anthonyajumelles** [comment]
> Thanks! Did the sha change to or did we just get the file size wrong?

Sorry that was hilariously amateur of me but I blame a long day of work. I corrected the checksum as well!

**Comment by cbm755** [comment]
Yeah me too!

No worries, I was waiting for it to download to double check and I confirm this.  So merging.

thanks for this!

**Comment by cbm755** [comment]
For the record, I assume upstream changed the file, b/c we did test commit e853763ea70864e4fd51a57e186d401e58233bd6

**Comment by Lonsfor** [comment]
when i did test builds it didnt complain at me so i dont know what happened

**Pull request merged**
