### PR TITLE
Update org.srb2.SRB2Kart.yaml

### LINKED ISSUE #58: Freedesktop Platform 22.08 is EoL
Screenshot from 2024-09-28 21-28-03

"Please update to a supported runtime version"
I don't know...how hard that'll be? But probably wise to migrate to a newer branch of freedesktop, no?

### PR DESCRIPTION
**Pull request by nikotonn**
Test runtime-version on 23.08 to resolve #58

### CODE REVIEW

**Comment by cbm755** [comment]
bot, build

**Comment by cbm755** [comment]
I tried but got this error, perhaps it only lasts a few days
```
error: Can't load uri https://dl.flathub.org/build-repo/133896/org.srb2.SRB2Kart.flatpakref: Server returned status 404
```

**Comment by nikotonn** [comment]
Yeah that makes sense

**Comment by cbm755** [comment]
bot, build

**Comment by cbm755** [comment]
tested: basic gameplay, sounds, opengl karts.

not tested: multiplayer, discord-integration

**Comment by cbm755** [comment]
oops I tested 23.08 and my bump to 24.08 failed,

**Comment by cbm755** [comment]
@Lonsfor @ghisvail I'll merge this in 24 hours or so.  I've lightly tested and I think @nikotonn who sent this PR (thanks!) has also tested.

**Pull request merged**
